### ISSUE TITLE
[Bug]: MacOS Daemon exec path is hardcoded, fails for brew install

### ISSUE THREAD

**Issue by ChibangLW** [gravitl/netmaker#1228]
### What happened?

If using the netclient installed with brew the daemon fails silently. I think the error is [here](https://github.com/gravitl/netmaker/blob/39c4502fc434090fd2832b5773dca650eadfd2de/netclient/daemon/macos.go#L96), where a different path is needed for homebrew installations (/opt/homebrew/bin/netclient). It also looks like `/opt/homebrew/bin` is needed in the path at the [end](https://github.com/gravitl/netmaker/blob/39c4502fc434090fd2832b5773dca650eadfd2de/netclient/daemon/macos.go#L109).

I would expect a LaunchDeamon config depending on the exec path.

### Version

v0.14.3

### What OS are you using?

Mac

### Contributing guidelines

- [X] Yes, I did.

**Comment by mritd** [comment]
I tried to modify the install code of netclient, but I have a little problem:

If we rely on brew, then install daemon logic should not be implemented in the code, so that all changes are guaranteed to be consistent;

If we do not completely rely on brew, we should do the installation logic, such as automatic installation of wireguard-go, etc.;

I prefer to complete the repair in the brew repository, and then remove the installation logic of the daemon on the mac platform (the command line can print a help prompt); brew can guarantee consistency, and brew can maintain services and things for us.

**Comment by afeiszli** [comment]
Client now installs at /opt/homebrew/bin/netclient; closing this issue
