### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by wangze-TIM** [gravitl/netmaker#1507]
### What happened?

root@iZ7xv1kebslutgvscqzrz3Z:~# ./netclient join  -t  token
[netclient] 2022-09-02 17:36:46 joining my-net at  
[netclient] 2022-09-02 17:36:46 error installing:  error creating node Post "https:///api/nodes/my-net": http: no Host in request URL 
[netclient] 2022-09-02 17:36:47 removed systemd remnants if any existed 

### Version

v0.15.0

### What OS are you using?

Linux

### Contributing guidelines

- [X] Yes, I did.

**Comment by afeiszli** [comment]
look at your token: echo (token) | base64 -d

It is likely missing the apiconnstring field.

This is probably due to missing the correct field in your docker compose: SERVER_API_CONN_STRING

If this field is missing, add and restart the server.

You will need to create a new access token, since the field is added only on creation.

**Comment by wangze-TIM** [comment]
I am using binary deployment, how to configure the configuration file

**Comment by wangze-TIM** [comment]
I saw it in your code, the configuration on the official website is different from your code

**Comment by afeiszli** [comment]
Please point to where the configuration is wrong in our docs so we can update it.

**Comment by wangze-TIM** [comment]
https://docs.netmaker.org/server-installation.html#nodocker   The address is this URL  
Your configuration document is this apiconnection, I see your code is apiconn
