### ISSUE TITLE
Netmaker Incorrect Backend URL 

### ISSUE THREAD

**Issue by comatoasted** [gravitl/netmaker#153]
I've been having a hard time parsing why exactly this occurs on differing deployments with nearly exact specifications.

The issue comes up upon initial install.

1. Install as normal.
2. edit docker-compose.yml to include public-IP of a cloud provisioned server.
3. Boot it up.
4. Incorrect Backend URL that includes the IP.

Do this on some other server. No issues. Same configuration. 

Edit: Forgot to mention, all ports are open and whatnot. I did see the troubleshooting guide about this.

**Comment by afeiszli** [comment]
Apologies, the UI message is misleading. It will display the message "Incorrect Backend URL" regardless of what error is occurring on the backend. This could be any reason related, but if all ports are open and it is the correct address, this is likely a failed API call. I would open a developer console on the UI and take a look at what messages are logged when you refresh the page. I would guess most likely the issue is due to authentication failing.

**Comment by afeiszli** [comment]
This could also just mean that the server is not even up and running, so it is worth checking to make sure the netmaker server logs.

**Comment by afeiszli** [comment]
Any luck?

**Comment by comatoasted** [comment]
It actually was misleading it turned out to be a combination of things regarding things the cloud provider had on their base image for ubuntu. This is why it worked with other images/providers. Its pretty obvious, but the logs actually did explain the error to a degree. I suppose the whole 'incorrect backend url' screen provided threw me off the trail because it suggested an error that was documented and that wasn't the case.

Sorry for slow response, life happened. Thanks though! Running this for about 5 different networks and 30 or so hosts in them. Solid so far, tested against Wireguard pure and saw no real difference. Works great!
