### ISSUE TITLE
[BUG]: iptables postUp and postDown rules should be inserted

### ISSUE THREAD

**Issue by voroskoi** [gravitl/netmaker#1667]
### What happened?

Hi,

First things first: Netmaker is amazing, thank you!

I usually set up my firewall rules in the following method:
ACCEPT something
ACCEPT something else
LOG everything reaches this rule
DROP everything reaches this rule

The policy is ACCEPT, so I can flush everything and start over without locking myself out.

Because netmaker rules are appended they all go after the DROP rule and do not take effect.

Is there any particular reason for this? For my use case inserting would be better, but I am not sure if it has any drawback. Are You open to change this behavior?

Thanks,

### Version

v0.16.1

### What OS are you using?

Linux

### Contributing guidelines

- [X] Yes, I did.

**Comment by afeiszli** [comment]
This is worth considering, but could have considerable consequences so would need a good amount of testing.

In the meantime, you can turn RCE="on" in your docker compose (env section) and edit the postup/postdown commands to use "-I" instead of "-A".

**Comment by bondjames12** [comment]
Just wanted to add to this. I am running an ingress netclient in docker along with lots of other docker containers binding to IP on nm-main interface. I enable ufw firewall to block WAN in traffic from internet. This results in ingress traffic not being forwarded correctly because the iptables -A FORWARD -i nm-main -j ACCEPT are appended. If run the same but insert instead of append ingress traffic works.

My ufw rules are:
To                         Action      From
--                         ------      ----
22/tcp                  ALLOW       Anywhere
51821:51899/udp     ALLOW       Anywhere

**Comment by mattkasun** [comment]
Netclient no longer uses postup/postdown commands
