### ISSUE TITLE
[Bug]: ext. Client-Routing does not work if you configure Ingress Gateway after adding additional Nodes

### ISSUE THREAD

**Issue by ChrisStro** [gravitl/netmaker#1677]
### What happened?

if you doesn't enable your ingress-gateway  before adding additional nodes, traffic of external client will not pass the ingress-gateway

### Version

v0.16.1

### Contributing guidelines

- [X] Yes, I did.

**Comment by mattkasun** [comment]
this is expected behaviour,  when an ext client is created the configuration generated is a snapshot of the network at that point in time.  

If you change the network after adding ext clients and you wish those ext clients to have the new network configuration, you have to delete and recreate the ext clients.

**Comment by ChrisStro** [comment]
This doesn't work, I've recreated the configuration several times. The point is when Ingress activates. It's easy to reproduce.
is working:
Enable Ingress on the first node --> add multiple nodes --> create external client configuration --> route works
it does not work:
add multiple nodes --> enable/add ingress --> create ext-client configuration --> traffic only hits the first node

Seems like a configuration is not updated when the ingress gateway is later activated

Maybe for your information: I'm using Docker Netclient

**Comment by mattkasun** [comment]
interesting.... will check out
