### ISSUE TITLE
Not able to change endpoint address

### ISSUE THREAD

**Issue by Madic-** [gravitl/netmaker#174]
I would like to change the IPv4 endpoint address on one system to an IPv6 address because the IPv4 address is behind a cgnat.
When changing the endpoint address via the webui to an IPv6 Adress, a few minutes later the endpoint address resets back to the previous IPv4 address. I also tried changing the endpoint address in the netclient config on the host. But it also resets after a few minutes to the previous address.

**Comment by afeiszli** [comment]
This is likely due to the "roaming" setting on the netclient. Roaming is enabled by default, which will detect the public IP and change the endpoint value if it does not match.

You can disable roaming in the config file by setting roaming: off.

While installing, the flag is `netclient join -t <token> -roaming off`

**Comment by Madic-** [comment]
Thank you. That helped. I've also seen that on join it's now possible to directly configure the endpoint. That's great!
With 0.5 the overall cli experience is far better than before. Thank you for that
