### ISSUE TITLE
Enable "allowed IPs" to be set

### ISSUE THREAD

**Issue by ArseniiPetrovich** [gravitl/netmaker#194]
For now configuration file ignores this completely.
For our specific use case described here => https://github.com/ubuntu/microk8s/issues/2402 we need our VPN-enabled nodes to know about each other primary IPs. As a workaround we are going to use a script that will alter WG configuration after each restart, but this will not be handy when the number of nodes increases.

**Comment by afeiszli** [comment]
Hi Arsenii, 

I am guessing you mean the AllowedIP's value in the Netclient config. This value does not do anything currently and should probably be removed. 

What are you attempting to set?

If it is the "VPN Address" on a given node, which the other nodes will use in their Peer->AllowedIPs section, that will be the "wgaddress" field rather than AllowedIPs.

If you would like to discuss this more you can join our discord and we can have a short call to discuss: https://discord.gg/XE9Sz49e

**Comment by afeiszli** [comment]
Based on discussion, we will leave this as an enhancement for the next version. We will keep AllowedIPs, which will be a string list of ip addresses and domains. We have to be a little careful. Adding one incorrectly formatted address could break peer configuration on the client side for all servers.

**Comment by afeiszli** [comment]
Basically, any ADDITIONAL addresses for a given node (besides the private address) will be added in AllowedIPs

**Comment by pete1019** [comment]
Has this been added?
Thanks

**Comment by dillon-carns** [comment]
@pete1019 I just put in the hotfix for this. afeiszli will review and likely merge later today.

**Comment by dillon-carns** [comment]
This has been added!
