### ISSUE TITLE
Kubernetes install - no support for rqlite

### ISSUE THREAD

**Issue by rubencosta** [gravitl/netmaker#235]
I wanted to deploy netmaker with k8s using https://github.com/gravitl/netmaker/blob/master/kube/netmaker-template.yaml and found a couple of setbacks 
1. MongoDB is still included instead of rqlite in the template
2. Netmaker does not offer configuration for rqlite server url. It always tries to connect to http://localhost:4001

**Comment by afeiszli** [comment]
Fixed in https://github.com/gravitl/netmaker/releases/tag/latest

There are two versions: netmaker-template and netmaker-template-udp.
   - netmaker-template deploys without client mode, meaning udp hole punching is not an option
     - this is necessary because otherwise the server must be tied to a single node and mount tons of system folders
   - netmaker-template-udp deploys with client mode, meaning udp hole punching is enabled
      - this deployment should be treated carefully and should be deployed only on a specified node (node selector).
