### ISSUE TITLE
[Bug]: Clients can't access other Clients upgrading to 20.6 from 17.1

### ISSUE THREAD

**Issue by MatthewReed303** [gravitl/netmaker#2543]
I have just update my server and clients and have tried to reconfigure everything as it was to find out I can no longer use Relays? I suspect this is my issue since my clients are on cellular networks and Starlink etc Do I have to now buy the enterprise version for my homelab etc I run NM on a Vultr VPS and was setup as a relay since my homelab is on the starlink end and my clients are cellular on 4G connections etc Is there another way to get these connections to work without using the relay feature? 

### Version

v0.20.6

**Comment by cocoonkid** [comment]
I need to know the same. The relay feature seems to be only available in the EE?
Or can we self hoster work around the issue with the TURN servers?

I still wasn't able to solve it but I went with zerotier self hosted controller for now as a workaround for devices not able to join otherwise.

I did not yet connect them to the NM network but that is certainly possible.

**Comment by mattkasun** [comment]
TURN has replaced Relays.
