### ISSUE TITLE
Node Editing in UI

### ISSUE THREAD

**Issue by mattkasun** [gravitl/netmaker#30]
The following fields appear to be editable in the UI but if changes are made and saved, the values revert back:
applicable to:

1. Default Listen Port
2. Default KeepAlive

If these fields are not editable, they should be non-editable in the GUI like NodeLastModified and GroupLastModified

**Comment by afeiszli** [comment]
adding to v0.2 fix list

**Comment by afeiszli** [comment]
Unable to replicate in develop branch. This may have been fixed by some changes to netclient and the API, but I changed both values, and they persisted, showing in the local netconfig file as well as in the active wireguard configuration. I think we can close this for  now but you can test with develop and reopen if necessary.
