### ISSUE TITLE
netmaker updates need to be easier

### ISSUE THREAD

**Issue by pete1019** [gravitl/netmaker#404]
Thanks for all the work so far!

Netmaker Server:
Updates need to be easier.
Best would be to integrate the possibility to just Update via the nm-quick.sh

Same for netclient. Easier update.

Thanks a lot

**Comment by bsherman** [comment]
I've had some thoughts about this. Specifically about the netclient update.

Suggested workflow:
- assumption: checkin/pull provides server version for each network
- when netclient does a checkin, if all of the joined networks are newer than the version of netclient
- select the lowest common version number provided
- netclient should download the selected version of netclient, ideally verify a checksum of some kind, then replace the binary at `/etc/netclient/netclient`
- a new setting option should exist `--enable-autoupgrade` default to true, but can be set to false upon install. This would disalbe this feature
- the systemd netclient.timer will use the new version for next checkin

**Comment by afeiszli** [comment]
I'm going to close this due to a couple of changes we've added in 0.14:
1. upgrade via packages - package installers now allow you up upgrade clients without manual intervention
2. upgrade logic - there is now logic in the client that will make appropriate model changes while upgrading to avoid conflicts between versions
