### ISSUE TITLE
Can a single node be used as an ingress gateway and egress gateway at present?

### ISSUE THREAD

**Issue by wnark** [gravitl/netmaker#517]
just like this
![image](https://user-images.githubusercontent.com/24355466/143534430-535bef04-6a0c-4f06-a76b-3fe99e020e59.png)
After using a single node as the ingress gateway and egress gateway, the parameters of the egress gateway I set before disappeared.
![image](https://user-images.githubusercontent.com/24355466/143534527-b836a05e-ee56-4d41-9c35-f017e190c012.png)

![image](https://user-images.githubusercontent.com/24355466/143534833-11687a1d-9f27-4e07-81ae-e0a56c27bcc5.png)

**Comment by wnark** [comment]
I think it might be the reason why I opened the relay?
My 10.23.28.3 and 10.23.28.4 cannot communicate with each other, so I turned on the 10.23.28.2 relay, and now 10.23.28.3 and 10.23.28.4 can ping through, but wg show can’t see 10.23.28.3, I don’t know. Is it a bug?
![image](https://user-images.githubusercontent.com/24355466/143585083-c66a24a8-d9e2-40a7-ac7d-e2e032f5f301.png)

**Comment by afeiszli** [comment]
We have not noticed any issues using a node as both ingress and egress , so this is likely due to the relay setup. 

To confirm, 10.23.28.3 is the egress gateway
                   10.23.28.2 is the relay

10.23.28.2 is a relay to 10.23.28.3.

In this scenario, 10.23.28.3 would not be visible to the other nodes.

One thing you should check: the egress gateway should still be visible from the relay node (10.23.28.2).

In any case, I think we should be able to make egress gateway work behind relay, but we have not enabled it yet.

**Comment by afeiszli** [comment]
Closing for now. Egress is now enabled behind relay.
