### ISSUE TITLE
Docker-Compose File assumes local deployment

### ISSUE THREAD

**Issue by mattkasun** [gravitl/netmaker#7]
The docker-compose.yml has BACKEND_URL set to 
`http://localhost:8081 for netmaker-ui`

This works for local deployment.  For a remote deployment this has to be updated to the public ip (or FQDN) of the remote machine. 

The BACKEND_URL should be set to the name of the netmaker container(or docker network ip), but this results in CORS violations and error message in netmaker-ui
`Incorrect backend detected. Please specify correct URL and refresh. Given: http://netmaker:8081`

**Comment by afeiszli** [comment]
I don't believe that would work. The requests are being sent from wherever you are accessing the interface (your browser) to the BACKEND_URL. 

If I'm accessing the netmaker-ui from my laptop at 22.22.22.2, and the backend server is at 33.33.33.33, I won't be able to reach the backend over the docker network, even though the frontend is hosted from 33.33.33.33, because the request is coming from 22.22.22.22. I think it either needs to be the public IP, or ideally a wireguard address that gets generated at startup (something I'd like to put in the next couple of releases).

Please let me know if you think I'm wrong here.

**Comment by mattkasun** [comment]
Yes, I misunderstood how the frontend works.

**Comment by yogeshbhoopathy** [comment]
Any work around for this?
