### ISSUE TITLE
[Need Help] I can't open the WebGUI

### ISSUE THREAD

**Issue by LxnChan** [gravitl/netmaker#783]
I install netmaker on my server, but I can't open WebGUI. It prompts me `ERR_SSL_PROTOCOL_ERROR`. I guess may the problem of certs. Open `http://[IP]:443` in directly is the same problem too.

Install method: nm-quick.sh
Version: Latest

How to delete or disable ssl?

**Comment by SmileEye** [comment]
Hello, did you solve it? 

I have the same problem and I don't know how to solve it.

**Comment by afeiszli** [comment]
@LxnChan @SmileEye the latest version uses Traefik as a proxy which may help with this issue. Are you still experiencing the problem?

**Comment by LxnChan** [comment]
@SmileEye @afeiszli I didn't have this problem when I switched to a non-mainland China server, probably because it couldn't connect to some APIs in the Mainland China and couldn't apply for a SSL certificate.

@afeiszli By the way does Netmaker (when deployed with Docker) download some files from github or elsewhere during configuration (besides the Docker image itself)? Due to the poor network environment in mainland China, it may not be possible to access some APIs or (required download from web) files in non-mainland China regions.

**Comment by afeiszli** [comment]
If you use the nm-quick script, then yes it will download some files from GitHub, including the docker-compose and the mosquitto.conf file.

As far as accessing APIs, LetsEnncrypt is probably the issue here. I am guessing in China it might be necessary to provide your own certificates for the proxy.

Finally, during runtime, both the netclient and netmaker need to reach out to an API to determine their public IP address. We have known this is an issue in China for some time, and have open PR's so that you can specify your own public IP service: #1432 #1426

**Comment by SmileEye** [comment]
@afeiszli @LxnChan  Thank you for your help, it has been solved, it may be related to my use of cloud servers in mainland China, I changed to an overseas server and it worked.
