### ISSUE TITLE
Increase network name max length

### ISSUE THREAD

**Issue by stianlaa** [gravitl/netmaker#910]
It would be very convenient to have more than 12 characters to identify a network. This would make it possible for us to have human-understandable name representing the intended use of the network.

This is a nice-to-have feature if you see a convenient way of achieving it. I assume the 12 character limit is due to some underlying system constraints, but perhaps one fix to such underlying constraints would be some sort of mapping table of sorts.

Regardless I was not able to find any pre-existing issue concerning this, so I figured an issue at least to discuss the possibility would be nice.

**Comment by afeiszli** [comment]
@stianlaa the limitation here is that we use the network name as the default interface name on the client side ("nm-" + "networkname"). On linux, an interface can max be 15 user-visible bytes, and "nm-" is 3 bytes, thus the 12 char limitation.

We could truncate the network name on the client side, but logic would get somewhat messy because we often use the interface name to determine the network on the client. Truncation could also lead to duplicate networks. Because of this, we may not want to do this, but I will leave open for now.

**Comment by stianlaa** [comment]
We expected that some underlying constraint was the reason for this, so I understand your point here, and your point regarding potential duplicate network names. Perhaps some short to medium description field would alleviate the problem somewhat, but perhaps that would be unnecessary fluff to some users.

As described in the issue its more of a nice-to-have feature than anything :smile:

**Comment by stianlaa** [comment]
Perhaps the long term solution will be to introduce a separation between name and network id, where id is always some sort of 12 character generated hash, and in any netclient cli view, or netmaker server view it would show the network name and the relevant hash? :thinking:

**Comment by uGiFarukh** [comment]
@stianlaa, the fix will be available in v0.20.6
network name length increased to 32

**Comment by stianlaa** [comment]
> @stianlaa, the fix will be available in v0.20.6 network name length increased to 32

Neat! Thanks for the followup.
