### ISSUE TITLE
Failed to create access key !

### ISSUE THREAD

**Issue by duoduo-CCIE** [gravitl/netmaker#934]
### Contact Details

fenghetaiyang@gmai.com

### What happened?

##docker-compose.yml

[https://github.com/CCIE-doudou/doudou/blob/cde5bff99bb81e4b09aa390187e6ed2a193b159c/docker-compose-nocaddy.yml](url)

version: "3.4"
services:
  netmaker:
    container_name: netmaker
    image: gravitl/netmaker:v0.12.0
    volumes:
      - dnsconfig:/root/config/dnsconfig
      - sqldata:/root/data
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    restart: always
    environment:
      SERVER_HOST: "10.1.11.31"
      #      SERVER_API_CONN_STRING: "api.NETMAKER_BASE_DOMAIN:443"
      #      SERVER_GRPC_CONN_STRING: "grpc.NETMAKER_BASE_DOMAIN:443"
      COREDNS_ADDR: "10.1.11.31"
      GRPC_SSL: "off"
      DNS_MODE: "on"
      #      SERVER_HTTP_HOST: "api.NETMAKER_BASE_DOMAIN"
      #      SERVER_GRPC_HOST: "grpc.NETMAKER_BASE_DOMAIN"
      API_PORT: "8081"
      GRPC_PORT: "50051"
      CLIENT_MODE: "on"
      MASTER_KEY: "abcdefghijklmn123456"
      CORS_ALLOWED_ORIGIN: "*"
      DISPLAY_KEYS: "on"
      DATABASE: "sqlite"
      #      NODE_ID: "netmaker-server-11"
      MQ_HOST: "mq"
      HOST_NETWORK: "off"
      MANAGE_IPTABLES: "on"
      PORT_FORWARD_SERVICES: "mq,dns,ssh" #,ssh
      VERBOSITY: "3"
    ports:
      - "51821-51825:51821-51825/udp"
      - "8081:8081"
      - "50051:50051"
  netmaker-ui:
    container_name: netmaker-ui
    depends_on:
      - netmaker
    image: gravitl/netmaker-ui:v0.12.0
    links:
      - "netmaker:api"
    ports:
      - "8082:80"
    environment:
            BACKEND_URL: "http://10.1.11.31:8081"
    restart: always
  coredns:
    depends_on:
      - netmaker
    image: coredns/coredns
    command: -conf /root/dnsconfig/Corefile
    container_name: coredns
    restart: always
    ports:
      - "10.1.11.31:53:53/udp"
      - "10.1.11.31:53:53/tcp"
    volumes:
      - dnsconfig:/root/dnsconfig
  mq:
    image: eclipse-mosquitto:2.0.14
    container_name: mq
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - /root/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_logs:/mosquitto/log
volumes:
  sqldata: {}
  dnsconfig: {}
  mosquitto_data: {}
  mosquitto_logs: {}
networks:
  default:
    name: netmaker_net1
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "192.168.201.0/24"

![image](https://user-images.githubusercontent.com/74661395/159332493-9bb8f2b6-b2e8-4ad4-9a35-478d5785ee5b.png)

![image](https://user-images.githubusercontent.com/74661395/159334485-633daeb1-90e9-45ac-adeb-ec846ed9fede.png)

![image](https://user-images.githubusercontent.com/74661395/159339013-0a57b9af-9749-4b06-8b7b-ef9464efe978.png)

### Version

v0.12.0

### What OS are you using?

Linux

### Relevant log output

```shell
netmaker     | 2022-03-21T17:41:38.840022309Z [netmaker] 2022-03-21 17:41:38 admin fetched all nodes they have access to
netmaker     | 2022-03-21T17:41:46.353461394Z [netmaker] 2022-03-21 17:41:46 admin fetched all nodes they have access to
netmaker     | 2022-03-21T17:41:53.629115541Z [netmaker] 2022-03-21 17:41:53 processed request error: cannot access comms network
netmaker     | 2022-03-21T17:41:53.753973595Z [netmaker] 2022-03-21 17:41:53 processed request error: cannot access comms network
netmaker     | 2022-03-21T17:41:53.839915538Z [netmaker] 2022-03-21 17:41:53 admin fetched all nodes they have access to
netmaker     | 2022-03-21T17:41:53.866308227Z [netmaker] 2022-03-21 17:41:53 processed request error: cannot access comms network
```

### Contributing guidelines

- [X] Yes, I did.

**Comment by ok-john** [comment]
Hey @duoduo-CCIE, you don't need to create access keys for the auto-generated network (often referred to as the comms network).

From the screenshots you added it looks like nodes sucesfully joined the comms network, however, the logs you shared suggest otherwise.

Can you clarify if this issue is for creating access keys or an inability for nodes to communicate over comms? The former is expected, the latter is suggestive of an bug. Thanks.

**Comment by duoduo-CCIE** [comment]
@ok-john 
thank you for your reply!
Yes, I only posted the log of creating the access key on the auto-generated network, and the log reflects the failure to create the key.
My second question for help is this: When a node where I have netclient installed joins the network I manually created, it will automatically join the network automatically generated by the netmaker server. As a result, two "nm-<network name>" are generated on my node. At the same time, the same node with the automatically generated name will also be displayed on the NODE label of the netmaker UI, causing the UI to be unsightly, :> |
The result is that the same node joins two networks with different names, and both networks can communicate, which does not match some of my security policies, which can easily lead to security problems. Not easy to manage.

**Comment by afeiszli** [comment]
@duoduo-CCIE the auto-generated network is the "comms" network. It's only route is to the server (does not add any other peers) and its only purpose is for secure client-server traffic. We originally had client-server traffic go over the same interface (for instance mynet-52) but this is an unstable design, because updates are sent over the same network that is updated. The comms network should be more stable. Hopefully this is ok for your security design.

For the access key, this is intentionally built in, but perhaps it shouldn't be. I'm going to re-label this as discussion / enhancement to reflect this. We may want to enable creation of access keys for the auto-generated network in case of troubleshooting.

One last note, yes this is less unsightly in the UI. We originally "hid" this network from view, but that makes troubleshooting difficult if something goes wrong with the network. For this reason it is displayed in the UI.

**Comment by duoduo-CCIE** [comment]
And if I knew how, this is where I'd say [thanks for everything]!!!
